baseURL = "https://mhathesh.me/"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
theme = "gokarna"
title = "mhathesh.me"
googleAnalytics = "G-X9KPV76EFD"

[params]
  accentColor = "#FF4D4D"
  showBackToTopButton = true
  togglePreviousAndNextButtons = "false"
  socialIcons = [
        {name = "github", url = "https://github.com/maddy023"},
        {name = "linkedin", url = "https://linkedin.com/in/madeshselva"},
      ]

[menu]
  [[menu.main]]
    # Display name
    name = "Posts"

    # Relative URL slug (appended to baseURL)
    url = "/posts/"

    # Lower weights are listed first in the menu (leftmost); higher weights are
    # listed last in the menu (rightmost)
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
